name: team2_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.6.0
  flutter_tts: ^4.2.1
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.10.0
  flutter_facebook_auth: ^7.1.1
  facebook_auth_desktop: ^2.1.1
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
